package:
  name: ardupilot_log_reader
  version: '0.1.0'

build:
  noarch: generic
  number: 0
  
source:
  path: ./

requirements:
  build:
    - python
    - setuptools
  host:
    - future
    - numpy
    - pandas
    - pymavlink
  run:
    - future
    - numpy
    - pandas
    - pymavlink
  test:
  imports:
    - ardupilot_log_reader
