name: Publish to PyPI and TestPyPI

on:
  push:
    branches:
      - 'dev'
      
jobs:
  build:
    name: Build and publish distribution
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Get tag
          run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          id: get_tag       

        - name: Install uv
          uses: astral-sh/setup-uv@v3
          with:
            enable-cache: true
            cache-dependency-glob: uv.lock
  
        - name: Set up Python
          run: uv python install 3.12
  
        - name: Build
          run: uv build

        - name: Publish to TestPyPI
          run: uv publish -t ${{ secrets.TEST_PYPI_TOKEN }} --publish-url https://test.pypi.org/legacy/