name: Publish to PyPI and TestPyPI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      
jobs:

  build:
    name: Build and publish distribution
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
  
        - name: Extract branch name
          shell: bash
          run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
          id: extract_branch
        
        - name: echo branch name
          run: echo ${{ steps.extract_branch.outputs.branch }}

        - name: Install uv
          uses: astral-sh/setup-uv@v3
          with:
            enable-cache: true
            cache-dependency-glob: uv.lock
  
        - name: Set up Python
          run: uv python install 3.12
  
        - name: Build
          run: uv build
        
        - name: Publish to PyPI
          if: ${{steps.extract_branch.outputs.branch  == 'main'}}
          run: uv publish -t ${{ secrets.PYPI_TOKEN }}
          
        - name: Publish to TestPyPI
          if: ${{steps.extract_branch.outputs.branch == 'dev'}}
          run: uv publish -t ${{ secrets.TEST_PYPI_TOKEN }} --publish-url https://test.pypi.org/legacy/