name: Publish to PyPI and TestPyPI

on:
  push:
    branches:
      - 'dev'
      
jobs:
  build:
    name: Build and publish distribution
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Get tag
          run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          id: current_tag
        
        - name: Get Last Tag
          run: |
            VERSION=$(git tag --sort=committerdate | grep -E '[0-9]' | tail -1 | cut -b 2-7)
            echo "RELEASE_VERSION=$(VERSION)" >> $GITHUB_OUTPUT
          id: last_major

        - name: Get Next Version
          run: |
            NEXTVERSION=$(echo ${VERSION} | awk -F. -v OFS=. '{$NF += 1 ; print}')
            echo "RELEASE_VERSION=$(VERSION)" >> $GITHUB_OUTPUT
          id: next_version

        - name: echo current version
          run: echo ${{ steps.current_tag.outputs.RELEASE_VERSION }}
        
        - name: echo last major tag
          run: echo ${{ steps.last_major.outputs.RELEASE_VERSION }}
        
        - name: echo next major tag
          run: echo ${{ steps.last_major.outputs.RELEASE_VERSION }}
 
        - name: Install uv
          uses: astral-sh/setup-uv@v3
          with:
            enable-cache: true
            cache-dependency-glob: uv.lock

        - name: Set up Python
          run: uv python install 3.12

        - name: Build
          run: uv build
        
        - name: Publish to TestPyPI
          if: ${{steps.last_major.outputs.RELEASE_VERSION == steps.current_tag.outputs.RELEASE_VERSION}}
          run: uv publish -t ${{ secrets.TEST_PYPI_TOKEN }} --publish-url https://test.pypi.org/legacy/