name: Publish to PyPI and TestPyPI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      
jobs:

  build:
    name: Build and publish distribution
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
  
        - name: Install uv
          uses: astral-sh/setup-uv@v3
          with:
            enable-cache: true
            cache-dependency-glob: uv.lock
  
        - name: Set up Python
          run: uv python install 3.12
  
        - name: Build
          run: uv build
        
        - name: echo ${{ github.ref_name }}
          run: echo ${{ github.ref_name }}

        - name: Publish to PyPI
          if: contains(github.ref_name, 'main')
          run: uv publish -t ${{ secrets.PYPI_TOKEN }}
          
        - name: Publish to TestPyPI
          if: contains(github.ref_name, 'dev')
          run: uv publish -t ${{ secrets.TEST_PYPI_TOKEN }}